name: composite-action
description: A composite action
runs:
  using: composite
  steps:
    - name: Run a one-line script
      shell: bash
      run: echo Hello, world!

    - name: Run a multi-line script
      shell: bash
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.