trigger: none

pool:
  vmImage: "ubuntu-latest"

# Build .NET application in src directory
steps:
  - checkout: self
    fetchDepth: 0

  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.x"

  - script: dotnet publish
    displayName: "Build the .NET application"
    workingDirectory: src/app

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: src/app/bin/Release/net8.0/publish
      artifact: "bin"
