trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      free -m
      echo ""
      df -h
      echo ""
      env -0 | sort -z | tr '\0' '\n'
    displayName: "Script: Dump environment"

  - script: |
      printenv | sort
    displayName: "Script: Dump environment (printenv)"
