trigger: none

resources:
  pipelines:
    - pipeline: build
      source: build
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: "ubuntu-latest"

variables:
  azureSubscription: "your-azure-subscription"
  appName: "your-app-name"
  resourceGroupName: "your-resource-group"

stages:
  - stage: Dev
    displayName: Development  Stage
    jobs:
      - job: DeployDev
        displayName: Deploy  to  Development
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"

          - script: |
              echo "Deploy application to the cloud here"
            displayName: "Deploy to cloud infrastructure"

  - stage: Test
    displayName: Testing Stage
    jobs:
      - job: DeployTest
        displayName: Deploy to Testing
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"

          - script: |
              echo "Deploy application to the cloud here"
            displayName: "Deploy to cloud infrastructure"

  - stage: Prod
    displayName: Production Stage
    jobs:
      - job: DeployProd
        displayName: Deploy to Production
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"

          - script: |
              echo "Deploy application to the cloud here"
            displayName: "Deploy to cloud infrastructure"
