parameters:
  - name: Environments
    type: object
    default:
      - name: Dev
      - name: Test
      - name: Prod

trigger: none

resources:
  pipelines:
    - pipeline: build
      source: \devops-tips-tricks\Build
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: "ubuntu-latest"

variables:
  azureSubscription: "your-azure-subscription"
  appName: "your-app-name"
  resourceGroupName: "your-resource-group"

stages:
  - ${{ each environment in parameters.Environments }}:
      - stage: ${{ environment.name }} # Loop through each environment
        displayName: ${{ environment.name }} Stage
        jobs:
          - job: Deploy${{ environment.name }} # Use the environment name to name the job
            displayName: Deploy to ${{ environment.name }}
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  targetPath: "$(Build.ArtifactStagingDirectory)"

              - script: |
                  echo "Deploy application to the cloud here"
                displayName: "Deploy to cloud infrastructure"
