name: CI2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      Configuration: Release

    steps:
      - uses: actions/checkout@v4

      - name: Call local composite action
        uses: ./.github/actions/composite-action
