name: Containers

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    container:
      #image: ubuntu:24.04
      image: flcdrg/ubuntu-with-docker:latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          MSSQL_SA_PASSWORD: ${{ env.MSSQL_SA_PASSWORD }}
          ACCEPT_EULA: Y

    env:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"

    steps:
      # Need this step because we're using container job that doesn't have Docker pre-installed
      - name: Docker Setup Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0

      - name: Wait for SQL Server to be ready
        run: |
          docker run --add-host=host.docker.internal:host-gateway flcdrg/wait-for-mssql:latest --username sa --password "$MSSQL_SA_PASSWORD"

      - name: Dump environment
        run: |
          free -m
          echo ""
          df -h
          echo ""
          env -0 | sort -z | tr '\0' '\n'
